[build]
  base = "client"
  publish = "client/dist"
  command = "npm run build"

[dev]
  framework = "vite"

[[redirects]]
  from = "/api/*"
  to = "https://full-escarta.onrender.com/api/:splat"
  status = 200
  force = true
