[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "vite" # or react, depending on what you use

[[redirects]]
  from = "/api/*"
  to = "https://full-escarta.onrender.com/api/:splat"
  status = 200
  force = true

# ✅ ADD THIS BLOCK 👇 to support React/Vite routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
